### ISSUE TITLE
Problem with import of geotiff

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/wps-remote#3]
After running a process successfully, producing an output tif, the tif shall be imported to geoserver so that it can be served.

The layer is registered and can be seen in the Layers list, but it cannot be previewed:

But, I can import the very same tif manually by clicking through the “Import Data” wizard in the GUI. Note: I had some permission problems beforehand, so the manual import also failed, but I solved these issues and can preview the manually imported layer.

![image](https://user-images.githubusercontent.com/571129/47210925-8385ba80-d394-11e8-82a9-06793d54e7b8.png)

Do you have any idea what I am missing?

Attached is the tif and the geoserver.log showing all infos for the job execution.

**Comment by afabiani** [comment]
Patch available at

https://github.com/geoserver/geoserver/commit/32ccc529da26c9adeaa5c4f24bbdfb7589d6491a
