### ISSUE TITLE
Make Geoserver query load status instead of waiting remote tasks to communicate it

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/wps-remote#6]
Refactor the way load status is exchanged between Geoserver and remote processes (pull approach instead of the current push scheme).

I report here the description from Verena:

"We think it is better to change from the current push scheme to a pull scheme, so that the remote wps plugin at geoserver side is responsible for querying the load status of attached processing machines in order to be able to feed in the requests.

Advantages:
 - On demand check, when necessary, no chatty process backends sending information in regular intervalls
 - Synced status, so that geoserver always has the most recent information on the load of processing backends. This will avoid the scenario here: User A starts a heavy process at time t=0, which is also blocking the whole processing machine (the same process is black listed!). User B starts a heavy process at time t=20. The processing backend is scheduled to tell geoserver the load average at time t=30, so the issued request of user B is causing the backend to crash. This is not a theoretic scenario but a real-world example in context of video rendering."

**Comment by giohappy** [comment]
Commits:
- https://github.com/geoserver/wps-remote/commit/60c4ca2e2f170ebcdac7f2c270783c1d3fdd539a
- https://github.com/geoserver/geoserver/commit/cdf7a094c29e6c11e7a59f49b9ee374e171a7718

didn't solve the problem, because stats from the bakend may not be reliable when the job execution doesn't report a high load (e.g. on startup or in particular job phases). If a new request arrive to WPS stats from the backend may wrongly report that load is ok and the new process can be run.

@afabiani we need to test if your suggestion of a "cool down time" is reliable, or if a better solution comes out.

**Comment by afabiani** [comment]
We are waiting for a reply from Michael if the architecture envisages only one GeoServer instance or a cluster of GeoServers.
In the latter case, we need to revise the architecture completely.
In general the "cool-down time", or any kind of active "timeout" is not really reliable in an asynchronous architecture.

**Comment by afabiani** [comment]
This is now implemented by the following technical proposal

https://docs.google.com/document/d/1ZtT7OFvtzbahzAle3FKe9HPKWEHYzChLptFcu-k2Gd0/edit?usp=sharing
