### ISSUE TITLE
Prepare a proposal to implement Integration testing

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/wps-remote#8]
According to our last call with Verean a proposal (with estimtes) must be submitted with a plan for the test framework extension, and Integration testing in particular.

**Comment by afabiani** [comment]
Proposal available here

https://docs.google.com/document/d/1QTdFFuFcBsG9McAJFXi0jG_v9LlzQJNi3bAGVYFFXQk/edit?usp=sharing
